__all__ = ["Dipole_Disturbance"]

import numpy as np
from typing import TYPE_CHECKING
from ADCS.satellite_hardware.disturbances.disturbance import Disturbance
from ADCS.satellite_hardware.errors.noise import Noise
from ADCS.orbits.orbital_state import Orbital_State
from ADCS.helpers.math_helpers import normalize

class Dipole_Disturbance(Disturbance):
    r"""
    **Magnetic Dipole Disturbance Model**

    Models the **disturbance torque** generated by a residual (parasitic) magnetic
    dipole interacting with Earth's geomagnetic field. This is a passive,
    non-actuated torque acting on the spacecraft body.

    **Physical Model**

    The body-frame torque is

    .. math::

        \mathbf{T}_d \;=\; \mathbf{m}_d \times \mathbf{B}_b,

    where

    - :math:`\mathbf{m}_d` is the residual dipole vector [A·m²],
    - :math:`\mathbf{B}_b` is the geomagnetic field in the body frame [T].

    Optionally, stochastic noise is added to :math:`\mathbf{m}_d` each step to
    represent modeling uncertainty or time variability.

    Parameters
    ----------
    dipole_torque : :class:`numpy.ndarray`
        Nominal magnetic dipole vector in body coordinates [A·m²], shape ``(3,)``.
    noise : :class:`~ADCS.satellite_hardware.errors.noise.Noise`
        Noise model instance used to perturb the nominal dipole vector.
    """

    def __init__(self, dipole_torque: np.ndarray, noise: Noise = None, estimate_dist: bool = False):
        r"""
        Initialize the dipole disturbance model.

        Parameters
        ----------
        dipole_torque : :class:`numpy.ndarray`
            Nominal magnetic dipole vector [A·m²], shape ``(3,)``.
        noise : :class:`~ADCS.satellite_hardware.errors.noise.Noise`
            Noise generator to inject random variations into the dipole.
        """
        self.torque_nominal = dipole_torque
        if noise:
            self.noise = noise
        else:
            self.noise = Noise()
        self.current_torque = self.torque_nominal.copy()

        super().__init__(estimate_dist=estimate_dist, estimated_vector_length=3)

    def update(self) -> None:
        r"""
        Update the current dipole vector by adding stochastic noise.

        At each simulation step,

        .. math::

            \mathbf{m}_d(t) \;=\; \mathbf{m}_{d,0} \;+\; \mathbf{n}(t),

        with :math:`\mathbf{m}_{d,0}` the nominal dipole and :math:`\mathbf{n}(t)` a
        noise realization. Call once per step before torque evaluation.
        """
        self.current_torque = self.torque_nominal + self.noise.get_noise()

    def torque(self, x: np.ndarray, os: Orbital_State) -> np.ndarray:
        r"""
        Compute the **magnetic dipole disturbance torque** in the body frame.

        Uses

        .. math::

            \mathbf{T}_d \;=\; \mathbf{m}_d \times \mathbf{B}_b.

        Parameters
        ----------
        x : :class:`numpy.ndarray`
            Full spacecraft state containing the attitude quaternion (used by
            :class:`~ADCS.orbits.orbital_state.Orbital_State` to produce
            :math:`\mathbf{B}_b`).
        os : :class:`~ADCS.orbits.orbital_state.Orbital_State`
            Provider of the body-frame magnetic field :math:`\mathbf{B}_b`.

        Returns
        -------
        :class:`numpy.ndarray`
            Disturbance torque vector [N·m], shape ``(3,)``.
        """
        vecs = os.get_state_vector(x=x)
        B_B = vecs["b"]
        return np.cross(self.current_torque, B_B)

    def torque_qjac(self, x: np.ndarray, os: Orbital_State) -> np.ndarray:
        r"""
        Jacobian of the torque with respect to the **attitude quaternion**.

        Let :math:`\mathbf{q}` be the quaternion inside :math:`x`.
        Since :math:`\mathbf{T}_d(\mathbf{q})=\mathbf{m}_d\times\mathbf{B}_b(\mathbf{q})`,

        .. math::

            \frac{\partial \mathbf{T}_d}{\partial \mathbf{q}}
            \;=\;
            \mathbf{m}_d \times
            \frac{\partial \mathbf{B}_b}{\partial \mathbf{q}}.

        Parameters
        ----------
        x : :class:`numpy.ndarray`
            State containing the attitude quaternion :math:`\mathbf{q}`.
        os : :class:`~ADCS.orbits.orbital_state.Orbital_State`
            Provides :math:`\partial \mathbf{B}_b / \partial \mathbf{q}`.

        Returns
        -------
        :class:`numpy.ndarray`
            Quaternion Jacobian ``∂T_d/∂q``, shape ``(3, 4)``.
        """
        vecs = os.get_state_vector(x=x)
        db_body__dq = vecs["db"]
        return np.cross(self.current_torque, db_body__dq)

    def torque_qqhess(self, x: np.ndarray, os: Orbital_State) -> np.ndarray:
        r"""
        Hessian of the torque with respect to the **attitude quaternion**.

        With :math:`\mathbf{T}_d(\mathbf{q})=\mathbf{m}_d\times\mathbf{B}_b(\mathbf{q})`,

        .. math::

            \frac{\partial^2 \mathbf{T}_d}{\partial \mathbf{q}^2}
            \;=\;
            \mathbf{m}_d \times
            \frac{\partial^2 \mathbf{B}_b}{\partial \mathbf{q}^2}.

        Parameters
        ----------
        x : :class:`numpy.ndarray`
            State containing the attitude quaternion :math:`\mathbf{q}`.
        os : :class:`~ADCS.orbits.orbital_state.Orbital_State`
            Provides :math:`\partial^2 \mathbf{B}_b / \partial \mathbf{q}^2`.

        Returns
        -------
        :class:`numpy.ndarray`
            Quaternion Hessian ``∂²T_d/∂q²``, shape ``(3, 4, 4)``.
        """
        vecs = os.get_state_vector(x=x)
        ddb_body__dqdq = vecs["ddb"]
        return np.cross(self.current_torque, ddb_body__dqdq)

    def torque_valjac(self, x: np.ndarray, os: Orbital_State) -> np.ndarray:
        r"""
        Jacobian of the torque with respect to the **dipole vector**.

        From :math:`\mathbf{T}_d = \mathbf{m}_d \times \mathbf{B}_b`,

        .. math::

            \frac{\partial \mathbf{T}_d}{\partial \mathbf{m}_d}
            \;=\; [\,\mathbf{B}_b\times\,],

        where :math:`[\,\cdot\times\,]` denotes the skew-symmetric cross-product matrix
        such that :math:`[\,\mathbf{a}\times\,]\mathbf{x}=\mathbf{a}\times\mathbf{x}`.

        Parameters
        ----------
        x : :class:`numpy.ndarray`
            Full spacecraft state (used by :mod:`ADCS.orbits` to form :math:`\mathbf{B}_b`).
        os : :class:`~ADCS.orbits.orbital_state.Orbital_State`
            Provider of :math:`\mathbf{B}_b`.

        Returns
        -------
        :class:`numpy.ndarray`
            Value Jacobian ``∂T_d/∂m_d``, shape ``(3, 3)``.
        """
        vecs = os.get_state_vector(x=x)
        B_B = vecs["b"]
        return np.cross(np.eye(3), B_B)

    def torque_qvalhess(self, x: np.ndarray, os: Orbital_State) -> np.ndarray:
        r"""
        Mixed second derivative with respect to **quaternion** and **dipole vector**.

        Using :math:`[\,\cdot\times\,]`,

        .. math::

            \frac{\partial^2 \mathbf{T}_d}{\partial \mathbf{q}\,\partial \mathbf{m}_d}
            \;=\;
            \frac{\partial}{\partial \mathbf{q}}\big[\,\mathbf{B}_b(\mathbf{q})\times\,\big]
            \;=\;
            \big[\,\tfrac{\partial \mathbf{B}_b}{\partial \mathbf{q}}\times\,\big].

        Parameters
        ----------
        x : :class:`numpy.ndarray`
            State containing the attitude quaternion :math:`\mathbf{q}`.
        os : :class:`~ADCS.orbits.orbital_state.Orbital_State`
            Provides :math:`\partial \mathbf{B}_b / \partial \mathbf{q}`.

        Returns
        -------
        :class:`numpy.ndarray`
            Mixed Hessian ``∂²T_d/∂q∂m_d``, shape ``(4, 3, 3)``.
        """
        vecs = os.get_state_vector(x=x)
        db_body__dq = vecs["db"]
        return np.cross(np.expand_dims(np.eye(3), 0), np.expand_dims(db_body__dq, 1))
