__all__ = ["Prop_Disturbance"]

import numpy as np
from typing import TYPE_CHECKING
from ADCS.satellite_hardware.disturbances.disturbance import Disturbance
from ADCS.satellite_hardware.actuators.noise import Noise
from ADCS.orbits.orbital_state import Orbital_State
from ADCS.helpers.math_helpers import normalize, normed_vec_jac, normed_vec_hess
from ADCS.orbits.universal_constants import EarthConstants

class Prop_Disturbance(Disturbance):
    r"""
    **Propulsion Disturbance Model**

    This class represents residual or imperfectly modeled **propulsion-induced torques**
    acting on the spacecraft body.  
    These torques can arise due to thrust misalignment, asymmetric propellant expulsion,
    or reaction forces during maneuvering.

    The model assumes a constant nominal disturbance torque with optional stochastic noise.

    **Model Overview**

    The total disturbance torque is expressed as:

    .. math::

        \mathbf{T}_{\mathrm{prop}} = \mathbf{T}_{0} + \mathbf{n}(t)

    where:

    - :math:`\mathbf{T}_{0}` — Nominal (constant) propulsion disturbance torque [N·m],
    - :math:`\mathbf{n}(t)` — Zero-mean stochastic noise term [N·m].

    This disturbance is independent of attitude or orbital parameters, and thus its
    attitude derivatives are zero.

    Parameters
    ----------
    torque_nominal : :class:`numpy.ndarray`
        Nominal propulsion disturbance torque vector [N·m], shape ``(3,)``.

    noise : :class:`~ADCS.satellite_hardware.actuators.noise.Noise`
        Noise model instance providing stochastic variations in the disturbance torque.

    Attributes
    ----------
    torque_nominal : :class:`numpy.ndarray`
        Constant nominal torque vector [N·m].

    current_torque : :class:`numpy.ndarray`
        Current disturbance torque (nominal + noise) [N·m].
    """

    def __init__(self, torque_nominal: np.ndarray, noise: Noise):
        r"""
        Initialize the propulsion disturbance model.

        Parameters
        ----------
        torque_nominal : :class:`numpy.ndarray`
            Constant nominal torque vector (3,) [N·m].

        noise : :class:`~ADCS.satellite_hardware.actuators.noise.Noise`
            Noise model instance providing additive random torque fluctuations.
        """
        self.torque_nominal = torque_nominal
        self.noise = noise
        self.current_torque = self.torque_nominal.copy()

    def update(self) -> None:
        r"""
        Update the current propulsion disturbance torque.

        Adds a random noise realization to the nominal torque vector:

        .. math::

            \mathbf{T}_{\mathrm{prop}}(t) = \mathbf{T}_{0} + \mathbf{n}(t)

        where :math:`\mathbf{n}(t)` is generated by the noise model.
        """
        self.current_torque = self.torque_nominal + self.noise.get_noise()

    def torque(self) -> np.ndarray:
        r"""
        Return the **current disturbance torque** due to propulsion effects.

        Since this model represents a static (non-attitude-dependent) torque,
        it directly returns the last updated value.

        Returns
        -------
        :class:`numpy.ndarray`
            Current propulsion disturbance torque [N·m], shape ``(3,)``.
        """
        return self.current_torque

    def torque_qjac(self) -> np.ndarray:
        r"""
        Compute the **Jacobian of the propulsion disturbance torque** with respect to the attitude quaternion.

        Since the torque is constant and not a function of orientation:

        .. math::

            \frac{\partial \mathbf{T}_{\mathrm{prop}}}{\partial q} = \mathbf{0}_{3 \times 4}

        Returns
        -------
        :class:`numpy.ndarray`
            Quaternion Jacobian matrix (3×4), all zeros.
        """
        return np.zeros((3, 4))

    def torque_qqHess(self) -> np.ndarray:
        r"""
        Compute the **Hessian of the propulsion disturbance torque** with respect to the attitude quaternion.

        Since :math:`\mathbf{T}_{\mathrm{prop}}` is constant:

        .. math::

            \frac{\partial^2 \mathbf{T}_{\mathrm{prop}}}{\partial q^2} = \mathbf{0}_{3 \times 4 \times 4}

        Returns
        -------
        :class:`numpy.ndarray`
            Quaternion Hessian tensor (3×4×4), all zeros.
        """
        return np.zeros((3, 4, 4))

