import numpy as np
import warnings
from typing import Union

from ADCS.satellite_hardware.actuators.actuator import Actuator
from ADCS.satellite_hardware.actuators.bias import Bias
from ADCS.satellite_hardware.actuators.noise import Noise
from ADCS.orbits.orbital_state import Orbital_State

class MTQ(Actuator):
    r"""
    **Magnetorquer (MTQ) Actuator Model**

    This class represents a single-axis **Magnetorquer (MTQ)** used for satellite attitude
    control. The MTQ generates torque through the interaction between its magnetic
    dipole moment and the Earth's geomagnetic field.

    **Physical Model**

    The torque produced by a magnetorquer is defined as:

    .. math::

        \mathbf{T}_{\mathrm{MTQ}} = -(\mathbf{B}_b \times \mathbf{m})

    where:

    - :math:`\mathbf{B}_b` — Magnetic field vector in the body frame [T]
    - :math:`\mathbf{m}` — Magnetic dipole moment vector [A·m²]
    - The negative sign accounts for the coil winding convention

    The commanded magnetic dipole moment is modeled as:

    .. math::

        \mathbf{m} = \mathbf{a}_{\mathrm{axis}} (u + b)

    where:

    - :math:`\mathbf{a}_{\mathrm{axis}}` — Magnetorquer unit axis direction  
    - :math:`u` — Commanded magnetic dipole magnitude [A·m²]  
    - :math:`b` — Bias term (constant or slowly varying)

    Combining both expressions gives:

    .. math::

        \mathbf{T}_{\mathrm{MTQ}} = -(\mathbf{B}_b \times \mathbf{a}_{\mathrm{axis}})(u + b) + \mathbf{n}

    where :math:`\mathbf{n}` is a random noise term representing actuator uncertainty.

    Parameters
    ----------
    axis : :class:`numpy.ndarray`
        Unit vector ``(3,)`` defining the magnetorquer alignment in the body frame.

    max_torque : float
        Maximum allowable torque magnitude [N·m].

    bias : :class:`~ADCS.satellite_hardware.actuators.bias.Bias`, optional
        Bias model representing constant or slowly varying offset in magnetic moment.

    noise : :class:`~ADCS.satellite_hardware.actuators.noise.Noise`, optional
        Noise model representing stochastic fluctuations in actuation.

    estimate_bias : bool, optional
        If ``True``, includes this actuator's bias term in the estimator state vector.
    """

    def __init__(
        self,
        axis: np.ndarray,
        max_torque: float,
        bias: Bias = None,
        noise: Noise = None,
        estimate_bias: bool = False,
    ) -> None:
        r"""
        Initialize a magnetorquer actuator.

        Parameters
        ----------
        axis : np.ndarray
            Unit vector (3,) defining the physical alignment of the magnetorquer 
            in the satellite body frame.

        max_torque : float
            Maximum allowable torque magnitude [N·m].

        bias : Bias, optional
            Bias model instance that describes slow variations or offsets in 
            magnetic moment (default is None).

        noise : Noise, optional
            Noise model instance representing stochastic actuation noise 
            (default is None).

        estimate_bias : bool, optional
            Whether to include this actuator’s bias in the state estimation 
            process (default is False).
        """
        super().__init__(axis=axis, u_max=max_torque, bias=bias, noise=noise, estimate_bias=estimate_bias)

    def torque(
        self,
        u: float,
        x: np.ndarray,
        os: Orbital_State,
    ) -> np.ndarray:
        r"""
        Compute the **torque generated by the magnetorquer**.

        The magnetorquer produces a body torque defined as:

        .. math::

            \mathbf{T}_{\mathrm{MTQ}} = -(\mathbf{B}_b \times \mathbf{a}_{\mathrm{axis}})(u + b) + \mathbf{n}

        where:

        - :math:`u` — Commanded magnetic moment magnitude [A·m²]  
        - :math:`b` — Actuator bias term (if ``bias=True``)  
        - :math:`\mathbf{n}` — Noise term (if ``noise=True``)  
        - :math:`\mathbf{B}_b` — Magnetic field vector in body frame [T]  
        - :math:`\mathbf{a}_{\mathrm{axis}}` — Magnetorquer axis direction

        Parameters
        ----------
        u : float
            Commanded magnetic moment [A·m²].

        x : :class:`numpy.ndarray`
            Full spacecraft state vector containing attitude quaternion.

        os : :class:`~ADCS.orbits.orbital_state.Orbital_State`
            Provides local magnetic field vector ``\mathbf{B}_b`` and related derivatives.

        bias : bool, optional
            Whether to include bias effects (default is False).

        noise : bool, optional
            Whether to include noise effects (default is False).

        Returns
        -------
        :class:`numpy.ndarray`
            Torque vector in body frame [N·m], shape ``(3,)``.

        Warnings
        --------
        Emits a :class:`UserWarning` if ``|u| > self.u_max``.
        """
        if abs(u) > self.u_max:
            warnings.warn("requested torque exceeds actuation limit")

        vecs = os.get_state_vector(x=x)
        b_body = vecs["b"]

        if self.bias:
            u += self.bias.get_bias(j2000=os.J2000)

        torque = -np.cross(b_body, self.axis) * u

        if self.noise:
            torque += self.noise.get_noise()

        return torque
    
    def storage_torque(self, u: float, j2000: float, bias: bool = False, noise: bool = False) -> float:
        return np.zeros((0,))

    def jacobians(
        self,
        u: float,
        x: np.ndarray,
        os: Orbital_State,
    ) -> Union[np.ndarray, np.ndarray]:
        r"""
        Compute **first-order derivatives (Jacobians)** of the magnetorquer torque.

        1. **Jacobian of torque w.r.t. control input**:

        .. math::

            \frac{\partial \mathbf{T}}{\partial u} = -(\mathbf{B}_b \times \mathbf{a}_{\mathrm{axis}})

        2. **Jacobian of torque w.r.t. base state** (e.g., attitude quaternion):

        .. math::

            \frac{\partial \mathbf{T}}{\partial \mathbf{x}} =
            \begin{bmatrix}
            \mathbf{0}_{3\times3} \\
            -\left( \frac{\partial \mathbf{B}_b}{\partial q} \times \mathbf{a}_{\mathrm{axis}} \right)(u + b)
            \end{bmatrix}

        Parameters
        ----------
        u : float
            Commanded magnetic moment [A·m²].

        x : :class:`numpy.ndarray`
            Satellite state (7,).

        os : :class:`~ADCS.orbits.orbital_state.Orbital_State`
            Orbital state instance providing field vectors and their derivatives.

        Returns
        -------
        tuple[np.ndarray, np.ndarray]
            - ``dT_du`` : shape ``(1, 3)`` — Jacobian of torque w.r.t. control input  
            - ``dT_dx`` : shape ``(7, 3)`` — Jacobian of torque w.r.t. base state
        """
        vecs = os.get_state_vector(x=x)
        b_body = vecs["b"]
        db_body__dq = vecs["db"]

        dtorq__du = -np.cross(b_body, self.axis).reshape((1, 3))

        biased_command = u + self.bias.get_bias(os.J2000)
        dtorq__dbasestate = np.vstack(
            [np.zeros((3, 3)), -np.cross(db_body__dq, self.axis) * biased_command]
        )

        return dtorq__du, dtorq__dbasestate

    def hessians(
        self,
        u: float,
        x: np.ndarray,
        os: Orbital_State,
    ) -> Union[np.ndarray, np.ndarray]:
        r"""
        Compute **second-order derivatives (Hessians)** of the magnetorquer torque.

        1. **Mixed derivative (torque w.r.t. control and state):**

        .. math::

            \frac{\partial^2 \mathbf{T}}{\partial u \, \partial \mathbf{x}} =
            \begin{bmatrix}
            \mathbf{0}_{3\times3} \\
            -\left( \frac{\partial \mathbf{B}_b}{\partial q} \times \mathbf{a}_{\mathrm{axis}} \right)
            \end{bmatrix}

        2. **Second derivative w.r.t. base state:**

        .. math::

            \frac{\partial^2 \mathbf{T}}{\partial \mathbf{x}^2} =
            -\left( \frac{\partial^2 \mathbf{B}_b}{\partial q^2} \times \mathbf{a}_{\mathrm{axis}} \right)(u + b)

        Parameters
        ----------
        u : float
            Commanded magnetic moment [A·m²].

        x : :class:`numpy.ndarray`
            Satellite state vector (7,).

        os : :class:`~ADCS.orbits.orbital_state.Orbital_State`
            Orbital state instance providing higher-order magnetic field derivatives.

        Returns
        -------
        tuple[np.ndarray, np.ndarray]
            - ``ddT_du_dx`` : shape ``(1, 7, 3)`` — Mixed Hessian of torque w.r.t. control and state  
            - ``ddT_dx2`` : shape ``(7, 7, 3)`` — Hessian of torque w.r.t. base state
        """
        vecs = os.get_state_vector(x=x)
        db_body__dq = vecs["db"]
        ddb_body__dqdq = vecs["ddb"]

        ddtorq__dudbasestate = np.vstack(
            [np.zeros((3, 3)), -np.cross(db_body__dq, self.axis)]
        ).reshape((1, 7, 3))

        biased_command = u + self.bias.get_bias(j2000=os.J2000)
        ddtorq__dbasestatedbasestate = np.zeros((7, 7, 3))
        ddtorq__dbasestatedbasestate[3:7, 3:7, :] = (
            -np.cross(ddb_body__dqdq, self.axis) * biased_command
        )

        return ddtorq__dudbasestate, ddtorq__dbasestatedbasestate
    

    def dtorq__du(self, u: float, x: np.ndarray, os: Orbital_State) -> np.ndarray:
        vecs = os.get_state_vector(x=x)
        b_body = vecs["b"]
        return -np.cross(b_body, self.axis).reshape((1, 3))
    
    def dtorq__dbasestate(self, u: float, x: np.ndarray, os: Orbital_State) -> np.ndarray:
        vecs = os.get_state_vector(x=x)
        db_body__dq = vecs["db"]

        biased_command = u + self.bias.get_bias(os.J2000)
        return np.vstack(
            [np.zeros((3, 3)), -np.cross(db_body__dq, self.axis) * biased_command]
        )
    
    def ddtorq__dudbasestate(self, u: float, x: np.ndarray, os: Orbital_State) -> np.ndarray:
        vecs = os.get_state_vector(x=x)
        db_body__dq = vecs["db"]

        return np.vstack(
            [np.zeros((3, 3)), -np.cross(db_body__dq, self.axis)]
        ).reshape((1, 7, 3))
    
    def ddtorq__dbasestatedbasestate(self, u: float, x: np.ndarray, os: Orbital_State) -> np.ndarray:
        vecs = os.get_state_vector(x=x)
        ddb_body__dqdq = vecs["ddb"]

        biased_command = u + self.bias.get_bias(j2000=os.J2000)
        ddtorq__dbasestatedbasestate = np.zeros((7, 7, 3))
        ddtorq__dbasestatedbasestate[3:7, 3:7, :] = (
            -np.cross(ddb_body__dqdq, self.axis) * biased_command
        )

        return ddtorq__dbasestatedbasestate

    def ddtorq__dbiasdbias(self, u: float, x: np.ndarray, os: Orbital_State) -> np.ndarray:
        if self.bias:
            return self.ddtorq__dudu(u=u, x=x, os=os)
        else:
            return np.zeros((0, 0, 3))
        
    def ddtorq__dbiasdbasestate(self, u: float, x: np.ndarray, os: Orbital_State) -> np.ndarray:
        if self.bias:
            return self.ddtorq__dudbasestate(u=u, x=x, os=os)
        else:
            return np.zeros((0, 7, 3))
        
    def ddtorq__dudh(self, u: float, x: np.ndarray, os: Orbital_State) -> np.ndarray:
        return np.zeros((1, 0, 3))
        
    


