__all__ = ["MTQ"]

import numpy as np
import warnings
from typing import Union, Dict

from ADCS.satellite_hardware.actuators.actuator import Actuator
from ADCS.satellite_hardware.actuators.bias import Bias
from ADCS.satellite_hardware.actuators.noise import Noise
from ADCS.satellite_hardware.disturbances.disturbance_mode import DisturbanceMode
from ADCS.orbits.orbital_state import Orbital_State

class MTQ(Actuator):
    r"""
    **Magnetorquer (MTQ) Actuator Model**

    This class represents a single-axis **Magnetorquer (MTQ)** used for satellite attitude
    control. The MTQ generates torque through the interaction between its magnetic
    dipole moment and the Earth's geomagnetic field.

    **Physical Model**

    The torque produced by a magnetorquer is defined as:

    .. math::

        \mathbf{T}_{\mathrm{MTQ}} = -(\mathbf{B}_b \times \mathbf{m})

    where:

    - :math:`\mathbf{B}_b` — Magnetic field vector in the body frame [T]
    - :math:`\mathbf{m}` — Magnetic dipole moment vector [A·m²]
    - The negative sign accounts for the coil winding convention

    The commanded magnetic dipole moment is modeled as:

    .. math::

        \mathbf{m} = \mathbf{a}_{\mathrm{axis}} (u + b)

    where:

    - :math:`\mathbf{a}_{\mathrm{axis}}` — Magnetorquer unit axis direction  
    - :math:`u` — Commanded magnetic dipole magnitude [A·m²]  
    - :math:`b` — Bias term (constant or slowly varying)

    Combining both expressions gives:

    .. math::

        \mathbf{T}_{\mathrm{MTQ}} = -(\mathbf{B}_b \times \mathbf{a}_{\mathrm{axis}})(u + b) + \mathbf{n}

    where :math:`\mathbf{n}` is a random noise term representing actuator uncertainty.

    Parameters
    ----------
    axis : :class:`numpy.ndarray`
        Unit vector ``(3,)`` defining the magnetorquer alignment in the body frame.

    max_torque : float
        Maximum allowable torque magnitude [N·m].

    bias : :class:`~ADCS.satellite_hardware.actuators.bias.Bias`, optional
        Bias model representing constant or slowly varying offset in magnetic moment.

    noise : :class:`~ADCS.satellite_hardware.actuators.noise.Noise`, optional
        Noise model representing stochastic fluctuations in actuation.

    estimate_bias : bool, optional
        If ``True``, includes this actuator's bias term in the estimator state vector.
    """

    def __init__(
        self,
        axis: np.ndarray,
        max_torque: float,
        bias: Bias = None,
        noise: Noise = None,
        estimate_bias: bool = False,
    ) -> None:
        r"""
        Initialize a magnetorquer actuator.

        Parameters
        ----------
        axis : np.ndarray
            Unit vector (3,) defining the physical alignment of the magnetorquer 
            in the satellite body frame.

        max_torque : float
            Maximum allowable torque magnitude [N·m].

        bias : Bias, optional
            Bias model instance that describes slow variations or offsets in 
            magnetic moment (default is None).

        noise : Noise, optional
            Noise model instance representing stochastic actuation noise 
            (default is None).

        estimate_bias : bool, optional
            Whether to include this actuator’s bias in the state estimation 
            process (default is False).
        """
        super().__init__(axis=axis, u_max=max_torque, bias=bias, noise=noise, estimate_bias=estimate_bias)

    def torque(
        self,
        u: float,
        x: np.ndarray,
        os: Orbital_State | Dict[str, np.ndarray],
        dmode: DisturbanceMode = None
    ) -> np.ndarray:
        r"""
        Compute the **torque generated by the magnetorquer**.

        The magnetorquer produces a body torque defined as:

        .. math::

            \mathbf{T}_{\mathrm{MTQ}} = -(\mathbf{B}_b \times \mathbf{a}_{\mathrm{axis}})(u + b) + \mathbf{n}

        where:

        - :math:`u` — Commanded magnetic moment magnitude [A·m²]  
        - :math:`b` — Actuator bias term (if ``bias=True``)  
        - :math:`\mathbf{n}` — Noise term (if ``noise=True``)  
        - :math:`\mathbf{B}_b` — Magnetic field vector in body frame [T]  
        - :math:`\mathbf{a}_{\mathrm{axis}}` — Magnetorquer axis direction

        Parameters
        ----------
        u : float
            Commanded magnetic moment [A·m²].

        x : :class:`numpy.ndarray`
            Full spacecraft state vector containing attitude quaternion.

        os : :class:`~ADCS.orbits.orbital_state.Orbital_State`
            Provides local magnetic field vector ``\mathbf{B}_b`` and related derivatives.

        bias : bool, optional
            Whether to include bias effects (default is False).

        noise : bool, optional
            Whether to include noise effects (default is False).

        Returns
        -------
        :class:`numpy.ndarray`
            Torque vector in body frame [N·m], shape ``(3,)``.

        Warnings
        --------
        Emits a :class:`UserWarning` if ``|u| > self.u_max``.
        """
        if abs(u) > self.u_max:
            warnings.warn("requested torque exceeds actuation limit")

        vecs = os.get_state_vector(x=x)
        b_body = vecs["b"]

        if dmode is None:
            dmode = DisturbanceMode(add_bias=True, add_noise=True, update_bias=True, update_noise=True)

        if self.bias and dmode.add_bias:
            u += self.bias.get_bias(j2000=os.J2000)
        if dmode.update_bias:
            self.bias._update_bias(j2000=os.J2000)

        torque = -np.cross(b_body, self.axis) * u

        if self.noise and dmode.add_noise:
            torque += self.noise.get_noise()
        if dmode.update_noise:
            self.noise._update_noise()

        return torque
    
    def storage_torque(self, u: float, x: np.ndarray, os: Orbital_State, dmode: DisturbanceMode = None) -> float:
        return np.zeros((0,))

    def jacobians(
        self,
        u: float,
        x: np.ndarray,
        os: Orbital_State,
    ) -> Union[np.ndarray, np.ndarray]:
        r"""
        Compute **first-order derivatives (Jacobians)** of the magnetorquer torque.

        1. **Jacobian of torque w.r.t. control input**:

        .. math::

            \frac{\partial \mathbf{T}}{\partial u} = -(\mathbf{B}_b \times \mathbf{a}_{\mathrm{axis}})

        2. **Jacobian of torque w.r.t. base state** (e.g., attitude quaternion):

        .. math::

            \frac{\partial \mathbf{T}}{\partial \mathbf{x}} =
            \begin{bmatrix}
            \mathbf{0}_{3\times3} \\
            -\left( \frac{\partial \mathbf{B}_b}{\partial q} \times \mathbf{a}_{\mathrm{axis}} \right)(u + b)
            \end{bmatrix}

        Parameters
        ----------
        u : float
            Commanded magnetic moment [A·m²].

        x : :class:`numpy.ndarray`
            Satellite state (7,).

        os : :class:`~ADCS.orbits.orbital_state.Orbital_State`
            Orbital state instance providing field vectors and their derivatives.

        Returns
        -------
        tuple[np.ndarray, np.ndarray]
            - ``dT_du`` : shape ``(1, 3)`` — Jacobian of torque w.r.t. control input  
            - ``dT_dx`` : shape ``(7, 3)`` — Jacobian of torque w.r.t. base state
        """
        vecs = os.get_state_vector(x=x)
        b_body = vecs["b"]
        db_body__dq = vecs["db"]

        dtorq__du = -np.cross(b_body, self.axis).reshape((1, 3))

        biased_command = u + self.bias.get_bias(os.J2000)
        dtorq__dbasestate = np.vstack(
            [np.zeros((3, 3)), -np.cross(db_body__dq, self.axis) * biased_command]
        )

        return dtorq__du, dtorq__dbasestate

    def hessians(
        self,
        u: float,
        x: np.ndarray,
        os: Orbital_State,
    ) -> Union[np.ndarray, np.ndarray]:
        r"""
        Compute **second-order derivatives (Hessians)** of the magnetorquer torque.

        1. **Mixed derivative (torque w.r.t. control and state):**

        .. math::

            \frac{\partial^2 \mathbf{T}}{\partial u \, \partial \mathbf{x}} =
            \begin{bmatrix}
            \mathbf{0}_{3\times3} \\
            -\left( \frac{\partial \mathbf{B}_b}{\partial q} \times \mathbf{a}_{\mathrm{axis}} \right)
            \end{bmatrix}

        2. **Second derivative w.r.t. base state:**

        .. math::

            \frac{\partial^2 \mathbf{T}}{\partial \mathbf{x}^2} =
            -\left( \frac{\partial^2 \mathbf{B}_b}{\partial q^2} \times \mathbf{a}_{\mathrm{axis}} \right)(u + b)

        Parameters
        ----------
        u : float
            Commanded magnetic moment [A·m²].

        x : :class:`numpy.ndarray`
            Satellite state vector (7,).

        os : :class:`~ADCS.orbits.orbital_state.Orbital_State`
            Orbital state instance providing higher-order magnetic field derivatives.

        Returns
        -------
        tuple[np.ndarray, np.ndarray]
            - ``ddT_du_dx`` : shape ``(1, 7, 3)`` — Mixed Hessian of torque w.r.t. control and state  
            - ``ddT_dx2`` : shape ``(7, 7, 3)`` — Hessian of torque w.r.t. base state
        """
        vecs = os.get_state_vector(x=x)
        db_body__dq = vecs["db"]
        ddb_body__dqdq = vecs["ddb"]

        ddtorq__dudbasestate = np.vstack(
            [np.zeros((3, 3)), -np.cross(db_body__dq, self.axis)]
        ).reshape((1, 7, 3))

        biased_command = u + self.bias.get_bias(j2000=os.J2000)
        ddtorq__dbasestatedbasestate = np.zeros((7, 7, 3))
        ddtorq__dbasestatedbasestate[3:7, 3:7, :] = (
            -np.cross(ddb_body__dqdq, self.axis) * biased_command
        )

        return ddtorq__dudbasestate, ddtorq__dbasestatedbasestate
    

    def dtorq__du(self, u: float, x: np.ndarray, os: Orbital_State) -> np.ndarray:
        r"""
        First derivative :math:`\displaystyle \frac{\partial\boldsymbol{\tau}}{\partial u}`.

        **Model.** The actuator torque is modeled as
        :math:`\boldsymbol{\tau}(u,\mathbf{x}) = (u + b)\,\mathbf{a}\times\mathbf{B}_\mathcal{B}(\mathbf{q})`,
        where :math:`\mathbf{a}=\texttt{self.axis}` (unit), :math:`b=\texttt{bias.get_bias(J2000)}` is a
        scalar bias, and :math:`\mathbf{B}_\mathcal{B}(\mathbf{q})=\mathbf{C}(\mathbf{q})^\top\mathbf{B}_\text{ECI}` is the
        geomagnetic field expressed in the body frame. (Here :math:`\mathbf{C}(\mathbf{q})` maps body→ECI.)

        Since :math:`\boldsymbol{\tau}` is affine in :math:`u`, we have
        :math:`\frac{\partial\boldsymbol{\tau}}{\partial u}=\mathbf{a}\times\mathbf{B}_\mathcal{B}(\mathbf{q})`.

        **Returned form.** The implementation returns
        :math:`-\mathbf{B}_\mathcal{B}(\mathbf{q})\times\mathbf{a}`, which is equal to
        :math:`\mathbf{a}\times\mathbf{B}_\mathcal{B}(\mathbf{q})` by the identity
        :math:`\mathbf{x}\times\mathbf{y}=-\,\mathbf{y}\times\mathbf{x}`.

        Returns
        -------
        (1, 3) ndarray
            Row-Jacobian w.r.t. the scalar input :math:`u`.
        """
        vecs = os.get_state_vector(x=x)
        b_body = vecs["b"]
        return -np.cross(b_body, self.axis).reshape((1, 3))

    def dtorq__dbasestate(self, u: float, x: np.ndarray, os: Orbital_State) -> np.ndarray:
        r"""
        First derivative :math:`\displaystyle \frac{\partial\boldsymbol{\tau}}{\partial \mathbf{x}}`
        with :math:`\mathbf{x}=[\boldsymbol{\omega};\mathbf{q}] \in \mathbb{R}^7`.

        **Notation.**
        Let :math:`b=\texttt{bias.get_bias(J2000)}`, :math:`\mathbf{a}=\texttt{self.axis}`,
        :math:`\mathbf{B}_\mathcal{B}(\mathbf{q})=\mathbf{C}(\mathbf{q})^\top\mathbf{B}_\text{ECI}`,
        and :math:`D_\mathbf{q}\mathbf{B}_\mathcal{B}(\mathbf{q})\in\mathbb{R}^{4\times 3}` denote the Jacobian
        of :math:`\mathbf{B}_\mathcal{B}` w.r.t. the quaternion components (this is ``vecs["db"]``).
        Define the *rowwise cross* between a matrix :math:`\mathbf{M}\in\mathbb{R}^{n\times 3}` and a vector
        :math:`\mathbf{v}\in\mathbb{R}^3` as :math:`(\mathbf{M}\times\mathbf{v})_{i:}=\mathbf{M}_{i:}\times\mathbf{v}`.

        **Result.**
        Since :math:`\boldsymbol{\tau}(u,\mathbf{x}) = (u+b)\,\mathbf{a}\times\mathbf{B}_\mathcal{B}(\mathbf{q})`
        depends on :math:`\mathbf{q}` but not on :math:`\boldsymbol{\omega}`, we obtain

        .. math::

            \frac{\partial\boldsymbol{\tau}}{\partial\boldsymbol{\omega}}=\mathbf{0}_{3\times 3},\qquad
            \frac{\partial\boldsymbol{\tau}}{\partial\mathbf{q}}
            = (u+b)\,\mathbf{a}\times D_\mathbf{q}\mathbf{B}_\mathcal{B}(\mathbf{q})
            = -\,\big(D_\mathbf{q}\mathbf{B}_\mathcal{B}(\mathbf{q}) \times \mathbf{a}\big)\,(u+b).

        The implementation returns the vertically stacked matrix
        :math:`\begin{bmatrix}\mathbf{0}_{3\times 3}\\ -\,D_\mathbf{q}\mathbf{B}_\mathcal{B}\times\mathbf{a}\,(u+b)\end{bmatrix}`.

        Returns
        -------
        (7, 3) ndarray
            Rows correspond to :math:`(\partial/\partial\boldsymbol{\omega},\,\partial/\partial\mathbf{q})`.
        """
        vecs = os.get_state_vector(x=x)
        db_body__dq = vecs["db"]

        biased_command = u + self.bias.get_bias(os.J2000)
        return np.vstack(
            [np.zeros((3, 3)), -np.cross(db_body__dq, self.axis) * biased_command]
        )

    def ddtorq__dudbasestate(self, u: float, x: np.ndarray, os: Orbital_State) -> np.ndarray:
        r"""
        Mixed second derivative :math:`\displaystyle \frac{\partial^2\boldsymbol{\tau}}{\partial u\,\partial \mathbf{x}}`.

        **Derivation.**
        Because :math:`\boldsymbol{\tau}(u,\mathbf{x})=(u+b)\,\mathbf{a}\times\mathbf{B}_\mathcal{B}(\mathbf{q})`,

        .. math::

        \frac{\partial\boldsymbol{\tau}}{\partial u}=\mathbf{a}\times\mathbf{B}_\mathcal{B}(\mathbf{q})
        = -\,\mathbf{B}_\mathcal{B}(\mathbf{q})\times\mathbf{a}.

        Differentiating w.r.t. :math:`\mathbf{x}` gives

        .. math::

            \frac{\partial^2\boldsymbol{\tau}}{\partial u\,\partial\boldsymbol{\omega}}=\mathbf{0}_{1\times 3\times 3},\qquad
            \frac{\partial^2\boldsymbol{\tau}}{\partial u\,\partial\mathbf{q}}
            = \mathbf{a}\times D_\mathbf{q}\mathbf{B}_\mathcal{B}(\mathbf{q})
            = -\,\big(D_\mathbf{q}\mathbf{B}_\mathcal{B}(\mathbf{q})\times\mathbf{a}\big).

        **Returned form.** Implemented as
        :math:`\begin{bmatrix}\mathbf{0}_{3\times 3}\\ -\,D_\mathbf{q}\mathbf{B}_\mathcal{B}\times\mathbf{a}\end{bmatrix}`
        with an added leading singleton dimension.

        Returns
        -------
        (1, 7, 3) ndarray
            Mixed Hessian stacked by :math:`(\boldsymbol{\omega}, \mathbf{q})`.
        """
        vecs = os.get_state_vector(x=x)
        db_body__dq = vecs["db"]

        return np.vstack(
            [np.zeros((3, 3)), -np.cross(db_body__dq, self.axis)]
        ).reshape((1, 7, 3))

    def ddtorq__dbasestatedbasestate(self, u: float, x: np.ndarray, os: Orbital_State) -> np.ndarray:
        r"""
        Pure base-state Hessian :math:`\displaystyle \frac{\partial^2\boldsymbol{\tau}}{\partial \mathbf{x}\,\partial \mathbf{x}}`.

        **Notation.**
        Let :math:`D^2_{\mathbf{q}\mathbf{q}}\mathbf{B}_\mathcal{B}(\mathbf{q})\in\mathbb{R}^{4\times 4\times 3}` denote the
        Hessian of :math:`\mathbf{B}_\mathcal{B}` w.r.t. quaternion components (this is ``vecs["ddb"]``).

        **Derivation.**
        Since :math:`\boldsymbol{\tau}(u,\mathbf{x})=(u+b)\,\mathbf{a}\times\mathbf{B}_\mathcal{B}(\mathbf{q})`,
        all second derivatives involving :math:`\boldsymbol{\omega}` vanish and the only nonzero block is
        the quaternion–quaternion block:

        .. math::

            \frac{\partial^2\boldsymbol{\tau}}{\partial \mathbf{q}\,\partial \mathbf{q}}
            \;=\; (u+b)\,\mathbf{a}\times D^2_{\mathbf{q}\mathbf{q}}\mathbf{B}_\mathcal{B}(\mathbf{q})
            \;=\; -\,(u+b)\,\big(D^2_{\mathbf{q}\mathbf{q}}\mathbf{B}_\mathcal{B}(\mathbf{q})\times\mathbf{a}\big).

        The implementation fills the :math:`[3\!:\!7,\,3\!:\!7,:]` block with
        :math:`-\,(D^2_{\mathbf{q}\mathbf{q}}\mathbf{B}_\mathcal{B}\times\mathbf{a})\,(u+b)` and zeros elsewhere.

        Returns
        -------
        (7, 7, 3) ndarray
            Base-state Hessian; only the :math:`4\times 4` quaternion block is nonzero.
        """
        vecs = os.get_state_vector(x=x)
        ddb_body__dqdq = vecs["ddb"]

        biased_command = u + self.bias.get_bias(j2000=os.J2000)
        ddtorq__dbasestatedbasestate = np.zeros((7, 7, 3))
        ddtorq__dbasestatedbasestate[3:7, 3:7, :] = (
            -np.cross(ddb_body__dqdq, self.axis) * biased_command
        )

        return ddtorq__dbasestatedbasestate

    def ddtorq__dbiasdbias(self, u: float, x: np.ndarray, os: Orbital_State) -> np.ndarray:
        r"""
        Second derivative :math:`\displaystyle \frac{\partial^2\boldsymbol{\tau}}{\partial b^2}`.

        **Result.**
        With :math:`\boldsymbol{\tau}=(u+b)\,\mathbf{a}\times\mathbf{B}_\mathcal{B}(\mathbf{q})`, the dependence on
        :math:`b` is linear; hence :math:`\partial^2\boldsymbol{\tau}/\partial b^2=\mathbf{0}`. The method mirrors
        :meth:`ddtorq__dudu` when a bias model is present (all zeros there), and returns an empty
        :math:`(0,0,3)` array otherwise.

        Returns
        -------
        (1, 1, 3) or (0, 0, 3) ndarray
            Zero tensor if bias exists; empty when bias is not modeled.
        """
        if self.bias:
            return self.ddtorq__dudu(u=u, x=x, os=os)
        else:
            return np.zeros((0, 0, 3))

    def ddtorq__dbiasdbasestate(self, u: float, x: np.ndarray, os: Orbital_State) -> np.ndarray:
        r"""
        Mixed second derivative :math:`\displaystyle \frac{\partial^2\boldsymbol{\tau}}{\partial b\,\partial \mathbf{x}}`.

        **Result.**
        Since :math:`\boldsymbol{\tau}=(u+b)\,\mathbf{a}\times\mathbf{B}_\mathcal{B}(\mathbf{q})` and :math:`b` enters
        multiplicatively like :math:`u`, we have

        .. math::

            \frac{\partial^2\boldsymbol{\tau}}{\partial b\,\partial \mathbf{x}}
            \;=\;\frac{\partial^2\boldsymbol{\tau}}{\partial u\,\partial \mathbf{x}}
            \;=\; \begin{bmatrix}
            \mathbf{0}_{3\times 3}\\[2pt] \mathbf{a}\times D_\mathbf{q}\mathbf{B}_\mathcal{B}(\mathbf{q})
            \end{bmatrix}
            \;=\; \begin{bmatrix}
            \mathbf{0}_{3\times 3}\\[2pt] -\,D_\mathbf{q}\mathbf{B}_\mathcal{B}(\mathbf{q})\times\mathbf{a}
            \end{bmatrix}.

        The implementation returns :meth:`ddtorq__dudbasestate` when bias exists, and an empty
        :math:`(0,7,3)` tensor otherwise.

        Returns
        -------
        (1, 7, 3) or (0, 7, 3) ndarray
            Mixed Hessian w.r.t. bias and base state (or empty if no bias).
        """
        if self.bias:
            return self.ddtorq__dudbasestate(u=u, x=x, os=os)
        else:
            return np.zeros((0, 7, 3))

    def ddtorq__dudh(self, u: float, x: np.ndarray, os: Orbital_State) -> np.ndarray:
        r"""
        Mixed second derivative :math:`\displaystyle \frac{\partial^2\boldsymbol{\tau}}{\partial u\,\partial \mathbf{h}}`.

        **Result.**
        The actuator has no momentum-storage state in this model; hence
        :math:`\partial\boldsymbol{\tau}/\partial \mathbf{h}=\mathbf{0}` and therefore
        :math:`\partial^2\boldsymbol{\tau}/\partial u\,\partial \mathbf{h}=\mathbf{0}`.

        Returns
        -------
        (1, 0, 3) ndarray
            Empty along the storage-state dimension.
        """
        return np.zeros((1, 0, 3))



