import numpy as np
import warnings
from typing import Union

from ADCS.satellite_hardware.actuators.actuator import Actuator
from ADCS.satellite_hardware.actuators.bias import Bias
from ADCS.satellite_hardware.actuators.noise import Noise
from ADCS.orbits.orbital_state import Orbital_State

class MTQ(Actuator):
    r"""
    Magnetorquer (MTQ) actuator model for satellite attitude control.

    This class models the torque generated by a magnetorquer (MTQ) using the 
    cross product between the commanded magnetic dipole moment and the 
    geomagnetic field in the body frame.

    Mathematically, the torque produced by the magnetorquer is given by:

    .. math::

        \mathbf{T} = -(\mathbf{B}_b \times \mathbf{m})

    where:

    - :math:`\mathbf{B}_b` is the magnetic field vector in the body frame [T],
    - :math:`\mathbf{m}` is the magnetic dipole moment vector [A·m²],
    - The negative sign accounts for the direction convention (depends on winding).

    The commanded dipole moment is modeled as:

    .. math::

        \mathbf{m} = (\mathbf{a}_{\text{axis}}) \, (u + b)

    where:

    - :math:`\mathbf{a}_{\text{axis}}` is the magnetorquer unit vector direction,
    - :math:`u` is the commanded magnetic moment magnitude,
    - :math:`b` is the actuator bias (constant or slowly varying offset).

    The resulting torque (with bias and noise) can be expressed as:

    .. math::

        \mathbf{T}_{\text{MTQ}} = -(\mathbf{B}_b \times \mathbf{a}_{\text{axis}})(u + b) + \mathbf{n}

    where :math:`\mathbf{n}` is a noise term representing actuator uncertainty.
    """

    def __init__(
        self,
        axis: np.ndarray,
        max_torque: float,
        bias: Bias = None,
        noise: Noise = None,
        estimate_bias: bool = False,
    ) -> None:
        r"""
        Initialize a magnetorquer actuator.

        Parameters
        ----------
        axis : np.ndarray
            Unit vector (3,) defining the physical alignment of the magnetorquer 
            in the satellite body frame.

        max_torque : float
            Maximum allowable torque magnitude [N·m].

        bias : Bias, optional
            Bias model instance that describes slow variations or offsets in 
            magnetic moment (default is None).

        noise : Noise, optional
            Noise model instance representing stochastic actuation noise 
            (default is None).

        estimate_bias : bool, optional
            Whether to include this actuator’s bias in the state estimation 
            process (default is False).
        """
        super().__init__(axis=axis, u_max=max_torque, bias=bias, noise=noise, estimate_bias=estimate_bias)

    def torque(
        self,
        command: float,
        q: np.ndarray,
        os: Orbital_State,
        bias: bool = False,
        noise: bool = False,
    ) -> np.ndarray:
        r"""
        Compute the torque generated by the magnetorquer.

        The generated torque is computed as:

        .. math::

            \mathbf{T} = -(\mathbf{B}_b \times \mathbf{a}_{\text{axis}})(u + b) + \mathbf{n}

        where:

        - :math:`u` = commanded dipole moment magnitude [A·m²],
        - :math:`b` = bias term (if enabled),
        - :math:`\mathbf{n}` = noise vector (if enabled),
        - :math:`\mathbf{B}_b` = magnetic field in body coordinates [T],
        - :math:`\mathbf{a}_{\text{axis}}` = magnetorquer axis vector.

        Parameters
        ----------
        command : float
            Commanded magnetic moment along the magnetorquer axis [A·m²].

        q : np.ndarray
            Current satellite attitude quaternion (4,).

        os : Orbital_State
            Orbital state instance providing the local magnetic field vector.

        bias : bool, optional
            Whether to apply actuator bias (default is False).

        noise : bool, optional
            Whether to apply actuator noise (default is False).

        Returns
        -------
        np.ndarray
            Torque vector in body frame [N·m], shape (3,).
        """
        if abs(command) > self.u_max:
            warnings.warn("requested torque exceeds actuation limit")

        vecs = os.get_state_vector(q0=q)
        b_body = vecs["b"]

        if bias:
            command += self.bias.get_bias(j2000=os.J2000)

        torque = -np.cross(b_body, self.axis) * command

        if noise:
            torque += self.noise.get_noise()

        return torque

    def jacobians(
        self,
        command: float,
        q: np.ndarray,
        os: Orbital_State,
    ) -> Union[np.ndarray, np.ndarray]:
        r"""
        Compute the first-order derivatives (Jacobian matrices) of the magnetorquer torque.

        **1. Torque w.r.t. control input:**

        .. math::

            \frac{\partial \mathbf{T}}{\partial u} = -(\mathbf{B}_b \times \mathbf{a}_{\text{axis}})

        **2. Torque w.r.t. base state (e.g., attitude quaternion):**

        .. math::

            \frac{\partial \mathbf{T}}{\partial \mathbf{x}} =
            \begin{bmatrix}
            \mathbf{0}_{3\times3} \\
            -(\frac{\partial \mathbf{B}_b}{\partial q} \times \mathbf{a}_{\text{axis}})(u + b)
            \end{bmatrix}

        Parameters
        ----------
        command : float
            Commanded magnetic moment [A·m²].

        q : np.ndarray
            Satellite attitude quaternion (4,).

        os : Orbital_State
            Orbital state instance providing field vectors and derivatives.

        Returns
        -------
        tuple[np.ndarray, np.ndarray]
            - dT/du : (1, 3) Jacobian of torque w.r.t. control input.
            - dT/dx : (7, 3) Jacobian of torque w.r.t. base state (position + attitude).
        """
        vecs = os.get_state_vector(q0=q)
        b_body = vecs["b"]
        db_body__dq = vecs["db"]

        dtorq__du = -np.cross(b_body, self.axis).reshape((1, 3))

        biased_command = command + self.bias.get_bias(os.J2000)
        dtorq__dbasestate = np.vstack(
            [np.zeros((3, 3)), -np.cross(db_body__dq, self.axis) * biased_command]
        )

        return dtorq__du, dtorq__dbasestate

    def hessians(
        self,
        command: float,
        q: np.ndarray,
        os: Orbital_State,
    ) -> Union[np.ndarray, np.ndarray]:
        r"""
        Compute the second-order derivatives (Hessian tensors) of the magnetorquer torque.

        **1. Mixed second derivative (torque w.r.t. control and state):**

        .. math::

            \frac{\partial^2 \mathbf{T}}{\partial u \, \partial \mathbf{x}} =
            \begin{bmatrix}
            \mathbf{0}_{3\times3} \\
            -\left(\frac{\partial \mathbf{B}_b}{\partial q} \times \mathbf{a}_{\text{axis}}\right)
            \end{bmatrix}

        **2. Second derivative w.r.t. base state:**

        .. math::

            \frac{\partial^2 \mathbf{T}}{\partial \mathbf{x}^2} =
            -\left(\frac{\partial^2 \mathbf{B}_b}{\partial q^2} \times \mathbf{a}_{\text{axis}}\right)(u + b)

        Parameters
        ----------
        command : float
            Commanded magnetic moment [A·m²].

        q : np.ndarray
            Satellite attitude quaternion (4,).

        os : Orbital_State
            Orbital state instance providing higher-order field derivatives.

        Returns
        -------
        tuple[np.ndarray, np.ndarray]
            - ddT/du_dx : (1, 7, 3) Hessian of torque w.r.t. control and state.
            - ddT/dx2 : (7, 7, 3) Hessian of torque w.r.t. state.
        """
        vecs = os.get_state_vector(q0=q)
        db_body__dq = vecs["db"]
        ddb_body__dqdq = vecs["ddb"]

        ddtorq__dudbasestate = np.vstack(
            [np.zeros((3, 3)), -np.cross(db_body__dq, self.axis)]
        ).reshape((1, 7, 3))

        biased_command = command + self.bias.get_bias(j2000=os.J2000)
        ddtorq__dbasestatedbasestate = np.zeros((7, 7, 3))
        ddtorq__dbasestatedbasestate[3:7, 3:7, :] = (
            -np.cross(ddb_body__dqdq, self.axis) * biased_command
        )

        return ddtorq__dudbasestate, ddtorq__dbasestatedbasestate