__all__ = ["RW"]

import numpy as np
import warnings
from ADCS.satellite_hardware.actuators.actuator import Actuator
from ADCS.satellite_hardware.actuators.bias import Bias
from ADCS.satellite_hardware.actuators.noise import Noise
from ADCS.orbits.orbital_state import Orbital_State

class RW(Actuator):
    r"""
    **Reaction Wheel (RW) Actuator Model**

    This class represents a single-axis **Reaction Wheel (RW)** used in satellite attitude
    control systems. It models how torque commands generate body torques and internal
    momentum changes through conservation of angular momentum.

    **Model Description**

    The reaction wheel applies a control torque to the spacecraft body by changing
    its spin rate. The torque applied to the spacecraft is defined as:

    .. math::

        \mathbf{T}_{\mathrm{RW}} = \mathbf{a}_{\mathrm{axis}} \, u

    where:

    - :math:`\mathbf{a}_{\mathrm{axis}}` — Reaction wheel spin axis (unit vector in body frame)
    - :math:`u` — Commanded motor torque input [N·m]

    The change in wheel angular momentum is governed by:

    .. math::

        \dot{\mathbf{h}} = -\mathbf{T}_{\mathrm{RW}}

    ensuring **angular momentum conservation** between the spacecraft and the wheel.

    Optional **bias** and **noise** models can be included to represent realistic
    actuator imperfections such as constant offsets or stochastic disturbances.

    Parameters
    ----------
    axis : :class:`numpy.ndarray`
        Unit vector ``(3,)`` defining the spin axis of the reaction wheel in the
        spacecraft body frame.

    max_torque : float
        Maximum torque u the motor can produce [N·m].

    J : :class:`numpy.ndarray`
        Moment of inertia of the wheel [kg·m²].

    h : :class:`numpy.ndarray`
        Current angular momentum of the wheel [N·m·s].

    h_max : :class:`numpy.ndarray`
        Maximum allowable stored momentum (saturation limit) [N·m·s].

    bias : :class:`~ADCS.satellite_hardware.actuators.bias.Bias`, optional
        Bias model instance representing constant or time-varying actuator offset.

    noise : :class:`~ADCS.satellite_hardware.actuators.noise.Noise`, optional
        Noise model instance representing stochastic torque fluctuations.

    estimate_bias : bool, optional
        If ``True``, includes actuator bias in the state estimation process.
    """

    def __init__(
        self,
        axis: np.ndarray,
        max_torque: float,
        J: float,
        h: np.ndarray,
        h_max: np.ndarray,
        bias: Bias = None,
        noise: Noise = None,
        estimate_bias: bool = False,
    ) -> None:
        r"""
        Initialize a Reaction Wheel actuator.

        Parameters
        ----------
        axis : np.ndarray
            Unit vector (3,) defining the spin axis of the reaction wheel in the 
            satellite body frame.

        max_torque : float
            Maximum torque the wheel motor can produce [N·m].

        J : float
            Wheel moment of inertia [kg·m²].

        h : np.ndarray
            Current angular momentum vector of the wheel [N·m·s].

        h_max : np.ndarray
            Maximum allowable angular momentum (saturation limit) [N·m·s].

        bias : Bias, optional
            Bias model instance representing constant or slowly varying offset 
            in the torque u (default is None).

        noise : Noise, optional
            Noise model instance representing stochastic noise in the torque 
            (default is None).

        estimate_bias : bool, optional
            Whether to include this actuator’s bias in the estimation process 
            (default is False).
        """
        self.J = J
        self.h = h
        self.h_max = h_max
        super().__init__(axis=axis, u_max=max_torque, bias=bias, noise=noise, estimate_bias=estimate_bias)

    def torque(self, u: float, x: np.ndarray, os: Orbital_State) -> float:
        r"""
        Compute the **reaction wheel body torque**.

        The torque generated by the wheel and applied to the spacecraft body is:

        .. math::

            \mathbf{T}_{\mathrm{RW}} = \mathbf{a}_{\mathrm{axis}} (u + b) + \mathbf{n}

        where:

        - :math:`u` — Commanded motor torque [N·m]
        - :math:`b` — Bias term (if ``bias=True``)
        - :math:`\mathbf{n}` — Stochastic noise (if ``noise=True``)
        - :math:`\mathbf{a}_{\mathrm{axis}}` — Wheel axis in body frame

        Parameters
        ----------
        u : float
            Commanded torque applied to the wheel motor [N·m].

        x : :class:`numpy.ndarray`
            Current spacecraft state vector.

        os : :class:`~ADCS.orbits.orbital_state.Orbital_State`
            Current orbital state, providing access to ``os.J2000`` for bias evolution.

        Returns
        -------
        :class:`numpy.ndarray`
            Torque vector applied to the spacecraft body [N·m], shape ``(3,)``.

        Warnings
        --------
        Emits a :class:`UserWarning` if ``|u| > self.u_max``.
        """
        if abs(u) > self.u_max:
            warnings.warn("requested torque exceeds actuation limit")

        torque = u

        if self.bias:
            torque += self.bias.get_bias(j2000=os.J2000)

        if self.noise:
            torque += self.noise.get_noise()

        return self.axis*torque

    def storage_torque(self, u: float, x: np.ndarray, os: Orbital_State) -> float:
        r"""
        Compute the **internal torque acting on the wheel** (equal and opposite to
        body torque).

        By conservation of angular momentum:

        .. math::

            \mathbf{T}_{\mathrm{wheel}} = -\mathbf{T}_{\mathrm{body}} = -\mathbf{a}_{\mathrm{axis}} \, u

        Parameters
        ----------
        u : float
            Commanded torque [N·m].

        Returns
        -------
        :class:`numpy.ndarray`
            Internal torque acting on the wheel, shape ``(3,)``.

        Warnings
        --------
        Emits a :class:`UserWarning` if ``|u| > self.u_max``.
        """
        if abs(u) > self.u_max:
            warnings.warn("RW Requested Torque exceeds actuation limit")
        
        command = u

        if self.bias:
            command += self.bias.get_bias(j2000=os.J2000)

        if self.noise:
            command += self.noise.get_noise()

        return -command
        

    def update_momentum(self, h: float) -> None:
        r"""
        Update the wheel’s stored angular momentum.

        Parameters
        ----------
        h : float
            New angular momentum [N·m·s].

        Warnings
        --------
        Emits a :class:`UserWarning` if ``h > self.h_max``.
        """
        if h > self.h_max:
            warnings.warn("RW Angular Momentum exceeds saturation limit")
        self.h = h

    def dtorq__du(self, u: float, x: np.ndarray, os: Orbital_State) -> np.ndarray:
        return self.axis.reshape((1,3))

    def dtorq__dh(self, u: float, x: np.ndarray, os: Orbital_State) -> np.ndarray:
        return np.zeros((1,3))
    
    def ddtorq__dudh(self, u: float, x: np.ndarray, os: Orbital_State) -> np.ndarray:
        return np.zeros((1, 1, 3))
    
    def ddtorq__dbiasdh(self, u: float, x: np.ndarray, os: Orbital_State) -> np.ndarray:
        if self.bias:
            return self.ddtorq__dudh(u=u, x=x, os=os)
        else:
            return np.zeros((0, 1, 3))
        
    def ddtorq__dbasestatedh(self, u: float, x: np.ndarray, os: Orbital_State) -> np.ndarray:
        return np.zeros((7, 1, 3))
    
    def ddtorq__dhdh(self, u: float, x: np.ndarray, os: Orbital_State) -> np.ndarray:
        return np.zeros((1, 1, 3))
    
    def dstor_torq__du(self, u: float, x: np.ndarray, os: Orbital_State) -> np.ndarray:
        return -np.ones((1,1))
    
    def dstor_torq__dbias(self, u: float, x: np.ndarray, os: Orbital_State) -> np.ndarray:
        if self.bias:
            return self.dstor_torq__du(u=u, x=x, os=os)
        else:
            return np.zeros((0, 1))
        
    def dstor_torq__dbasestate(self, u: float, x: np.ndarray, os: Orbital_State) -> np.ndarray:
        return np.zeros((7, 1))
    
    def dstor_torq__dh(self, u: float, x: np.ndarray, os: Orbital_State) -> np.ndarray:
        return np.zeros((1, 1))
    
    def ddstor_torq__dudu(self, u: float, x: np.ndarray, os: Orbital_State) -> np.ndarray:
        return np.zeros((1, 1, 1))
    
    def ddstor_torq__dudbias(self, u: float, x: np.ndarray, os: Orbital_State) -> np.ndarray:
        if self.bias:
            return self.ddstor_torq__dudu(u=u, x=x, os=os)
        else:
            return np.zeros((1, 0, 1))
        
    def ddstor_torq__dudbasestate(self, u: float, x: np.ndarray, os: Orbital_State) -> np.ndarray:
        return np.zeros((1, 7, 1))
    
    def ddstor_torq__dudh(self, u: float, x: np.ndarray, os: Orbital_State) -> np.ndarray:
        return np.zeros((1, 1, 1))
    
    def ddstor_torq__dbiasdbias(self, u: float, x: np.ndarray, os: Orbital_State) -> np.ndarray:
        if self.bias:
            return self.ddstor_torq__dudu(u=u, x=x, os=os)
        else:
            return np.zeros((0, 0, 1))
        
    def ddstor_torq__dbiasdbasestate(self, u: float, x: np.ndarray, os: Orbital_State) -> np.ndarray:
        if self.bias:
            return self.ddstor_torq__dudbasestate(u=u, x=x, os=os)
        else:
            return np.zeros((0, 7, 1))
        
    def ddstor_torq__dbiasdh(self, u: float, x: np.ndarray, os: Orbital_State) -> np.ndarray:
        if self.bias:
            return self.ddstor_torq__dudh(u=u, x=x, os=os)
        else:
            return np.zeros((0, 1, 1))

    def ddstor_torq__dbasestatedbasestate(self, u: float, x: np.ndarray, os: Orbital_State) -> np.ndarray:
        return np.zeros((7, 7, 1))
    
    def ddstor_torq__dbasestatedh(self, u: float, x: np.ndarray, os: Orbital_State) -> np.ndarray:
        return np.zeros((7, 1, 1))
    
    def ddstor_torq__dhdh(self, u: float, x: np.ndarray, os: Orbital_State) -> np.ndarray:
        return np.zeros((1, 1, 1))