# .github/workflows/ci.yml

name: Run Pytest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check_all_pytests:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout Repository
        uses: actions/checkout@v4

      - name: 🐍 Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: ⚙️ Create and Activate Virtual Environment
        run: |
          python -m venv .venv
          source .venv/bin/activate
          
      - name: 📦 Install Dependencies
        run: |
          source .venv/bin/activate
          pip install -r requirements.txt
          pip uninstall -y cmake
          
      - name: 🧪 Run Pytest
        run: |
          source .venv/bin/activate
          mkdir -p testing/artifacts
          pytest \
            testing/ \
            -m "not vslow" \
            --durations=0 \
            --durations-min=0.0 \
            --junitxml=testing/artifacts/pytest.xml

      - name: 📦 Upload Pytest JUnit XML
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-junit-report
          path: testing/artifacts/pytest.xml

      - name: 📋 Publish Test Summary
        if: always()
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: testing/artifacts/pytest.xml
